name: Compile AL Application
description: Compile the AL application and test app in a BC container.

inputs:
  CONTAINERNAME:
    required: true
  BC_USERNAME:
    required: true
  BC_PASSWORD:
    required: true
  Build_StagingDirectory:
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile Main App
      shell: pwsh
      run: |
        $RepoDir = Get-Location
        $srcPath = Join-Path $RepoDir "src"
        $password = ConvertTo-SecureString "${{ inputs.BC_PASSWORD }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ("${{ inputs.BC_USERNAME }}", $password)

        Write-Host "Compiling Main App..."
        Compile-AppInBcContainer -appProjectFolder $srcPath -containerName "${{ inputs.CONTAINERNAME }}" -credential $credential -GenerateReportLayout -ReportSuppressedDiagnostics

        $mainApp = Get-ChildItem -Path "$srcPath/output" -Filter "*.app" | Select-Object -First 1
        Copy-Item -Path $mainApp.FullName -Destination (Join-Path "${{ inputs.Build_StagingDirectory }}" "main.app") -Force

    - name: Compile Test App
      shell: pwsh
      run: |
        $RepoDir = Get-Location
        $testPath = Join-Path $RepoDir "test"
        $password = ConvertTo-SecureString "${{ inputs.BC_PASSWORD }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ("${{ inputs.BC_USERNAME }}", $password)

        Write-Host "Compiling Test App..."
        Compile-AppInBcContainer -appProjectFolder $testPath -containerName "${{ inputs.CONTAINERNAME }}" -credential $credential -GenerateReportLayout -ReportSuppressedDiagnostics

        $testApp = Get-ChildItem -Path "$testPath/output" -Filter "*.app" | Select-Object -First 1
        Copy-Item -Path $testApp.FullName -Destination (Join-Path "${{ inputs.Build_StagingDirectory }}" "test.app") -Force
